[package]
name = "solsys"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.23"
macroquad-profiler = "0.1.0"

[profile.dev]
opt-level = 0

[profile.release]
opt-level = 3
